openapi: 3.0.0
info:
  version: 1.0.0
  title: Openapy tutorial
tags:
  - name: user
    description: Everything about users
  - name: fruit
    description: Everything about fruit
paths:
  /users:
    get:
      tags:
        - user
      summary: Get all users
      operationId: getAllUsers
      parameters:
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/users/{userId}":
    get:
      tags:
        - user
      summary: Find user by ID
      description: Returns a single user
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
  /fruit:
    get:
      tags:
        - fruit
      summary: Get all fruits
      operationId: getAllFruits
      parameters:
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Fruit"

components:
  schemas:
    User:
      title: A User
      description: A User
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Fruit:
      title: A Fruit
      description: A Fruit
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
